using System.Xml.Serialization;

namespace EwsExchangeHelper.ExchangeItems
{
	public enum CategoryColor: byte
	{
		[XmlEnum("-1")]
		None,
		[XmlEnum("0")]
		Red,
		[XmlEnum("1")]
		Orange,
		[XmlEnum("2")]
		Peach,
		[XmlEnum("3")]
		Yellow,
		[XmlEnum("4")]
		Green,
		[XmlEnum("5")]
		Teal,
		[XmlEnum("6")]
		Olive,
		[XmlEnum("7")]
		Blue,
		[XmlEnum("8")]
		Purple,
		[XmlEnum("9")]
		Maroon,
		[XmlEnum("10")]
		Steel,
		[XmlEnum("11")]
		DarkSteel,
		[XmlEnum("12")]
		Gray,
		[XmlEnum("13")]
		DarkGray,
		[XmlEnum("14")]
		Black,
		[XmlEnum("15")]
		DarkRed,
		[XmlEnum("16")]
		DarkOrange,
		[XmlEnum("17")]
		DarkPeach,
		[XmlEnum("18")]
		DarkYellow,
		[XmlEnum("19")]
		DarkGreen,
		[XmlEnum("20")]
		DarkTeal,
		[XmlEnum("21")]
		DarkOlive,
		[XmlEnum("22")]
		DarkBlue,
		[XmlEnum("23")]
		DarkPurple,
		[XmlEnum("24")]
		DarkMaroon
	}
}